databases:
  - name: trabahadoor-db
    type: postgresql
    starterPlan: free

services:
  - type: web
    name: TrabahaDoor-backend
    env: node
    buildCommand: cd JobPortal/back-end && npm install
    startCommand: cd JobPortal/back-end && node server.js

  - type: web
    name: TrabahaDoor-front-end
    env: static
    staticPublishPath: JobPortal/front-end/build
    buildCommand: cd JobPortal/front-end && npm install && npm run build
